spring.application.name=auth-service
server.port=${AUTH_SERVICE_PORT}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID_AUTH_SERVICE}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.listener.type=single
spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI}
spring.threads.virtual.enabled=true
kafka.topic.user-registration-failed=${KAFKA_TOPIC_USER_REGISTRATION_FAILED}
kafka.topic.user-identity-created=${KAFKA_TOPIC_USER_IDENTITY_CREATED}
firebase.token.audience=${FIREBASE_TOKEN_AUDIENCE}
firebase.credentials=${FIREBASE_CREDENTIALS}
