beehive:
  jwt:
    secret: ${JWT_SECRET}
server:
  port: 8097
spring:
  application:
    name: beehive-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    name: beehive
    password: ${DATASOURCE_PASS}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: [ 'prometheus' ]
  metrics:
    tags:
      application: ${spring.application.name}